### PR TITLE
Passthrough all subtitles present, no main audio reencode.

### PR DESCRIPTION
**Pull request by eseglem**
Hopefully this is the direction you were headed. I know these are based off my personal preferences and may not completely match. The added audio track, and subtitles were important sticking points to me. With these changed I feel I can actually start doing my whole collection without having to go back and redo them later. This branch will also merge and work with #3, which is how I have been testing it. I moved it to its own branch in order to keep the pulls separate.

Added `--single` to stop reencoding the main AC3 as AAC. I do not feel that it is necessary to recreate the 5.1 audio as stereo within the transcode, media players can handle it on the fly. This seems to shave ~~almost 1GB from the~~ about 100MB file size, as well as some time. Not a huge deal, but it does help.

Changed code to passthrough all subtitles which are present in the mkv. This means there is no need to intelligently decide what subtitles are wanted in the program. Whichever subtitles are ripped will end up in the final mkv exactly as they show up in the original. The regex does allow for some language filtering later if that is a direction that is interesting. It would require more configuration and be slightly less turnkey though. I am leaning towards allow the user to decide while ripping it.

Added `--no-auto-burn` because I think it is better to leave the subtitles as text. They are now passed through so they still have the 'forced' tag for whatever media player you use to display them. This may still need more testing, my two test movies have not had any forced.

### CODE REVIEW

**Comment by andymccurdy** [comment]
I'd move the `--single` and `--no-auto-burn` options to the `TRANSCODE_OPTIONS` variable where all the constant options are. Other than that, this patch seems fine from a technical perspective.

I'd like to get @notthatwillsmith to provide feedback on the subtitle changes. He knows more about it than I do.

**Comment by eseglem** [comment]
Yeah, would make sense to move those to `TRANSCODE_OPTIONS` now that I see it. I was concentrating on those two functions and did not reread the constants. 
Looking in those options, I would consider removing the `--find-forced add` if the decision to go with passing all subtitles through is made. Not sure if it will cause a conflict, but would seem unnecessary.

**Comment by eseglem** [comment]
Was out of town, and let it transcode a bunch of discs while I was gone. Did a great job with the video and stayed up the whole time.
Seems I like all of the subtitle tracks make it through, but contain no text, so I will need to investigate this tomorrow and see what is going wrong with this method.

**Comment by andymccurdy** [comment]
Thanks for following up on this.

**Comment by eseglem** [comment]
It actually appears to be something specific to the transcode and Media Player Classic. DirectVobSub seems to be doing something weird with them. The subtitles work on original mkv, but do not after the transcode. They do however work in VLC and Plex after the transcode, which is really weird. It seems to be more of an issue with settings in MPC than the transcoder. 

Will still keep investigating, as I would prefer they work in everything, but not sure where the bug lies. I may actually try and transcode one in handbake manually to see what settings it take there, and then translate it back to the script.

**Comment by eseglem** [comment]
Not sure the best route forward on this. The subtitles work in MPC before transcoding, but even running default handbreak on them makes them stop working. That makes me thing it is some sort of incompatibility between the two. The subtitles work just fine with this method in VLC and Plex, so I think it is an acceptable solution. If that is the case then it is just a question of if passing through all the subtitles is the way the project wants to go. Definitely interested in hearing other people's opinions on it.

**Comment by James-Firth** [comment]
I like the idea of having all the subtitles passed through and not burned (or at least as an option). I'm ripping anime DVDs right now and would like to be able to have subtitles optional since it will depend on the language track I use.

**Comment by eseglem** [comment]
I have been using my branch for a while now about 60 movies or so, and have had no additional issues. Works great with Plex at least. There is just the confusion with MPC.
I have been doing the same thing with a few dual language animes as well. Seems to work. If you try it out let me know if you find any issues. I also just feel the subtitles look crisper / cleaner not being burned in.
I am contemplating ideas for options that get passed through to the transcoder, but have to be careful with settings, and newlines and things. That is for another discussion though.

**Comment by James-Firth** [comment]
I almost exclusively play videos through Plex these days so that's not a problem.
That's good to hear. I'm having some issues getting the VM to mount my folder/create the transcoder folders but that's better suited for the Tested forum if I can't get it to work later.

Agreed, I feel that subtitles look better when not burned in, though with movies that have the forced subtitles for certain scenes I could see the burn-in being useful.

In any event I'll try and give this another shot this week/next weekend when I actually have the time to spare to dig around in it. Thanks for posting this PR!

**Pull request closed without merging**
