### PR TITLE
Add intall.bat which prompts user for input values.

### PR DESCRIPTION
**Pull request by eseglem**
I have been unable to find a way to prompt users for input within vagrant, so I figured install scripts would be the next best thing.

I am not great with batch files, but this is what I have come up with so far. It defaults to the same values as the Vagrantfile (4/4096). It does add a default directory C:\transcoder for convenience. 

I also added the create flag within vagrant so the directory will be created on the host if it does not exist. I am still debating if this is a good thing, as it could lead to trouble if someone puts in a bad input, however it does make it less steps / easier.

I will probably try to do the same thing in a bash script sometime this weekend, but I am not much better at them than batch files.

### CODE REVIEW

**Comment by notthatwillsmith** [comment]
That's why we're avoiding as much OS-specific stuff as possible. An install.bat doesn't help people on OSX or Linux.

**Comment by eseglem** [comment]
Definitely understandable. OS specific may not be the best way forward. Testing everything becomes much more of a pain, and it is much more to keep track of. 
I am still looking into vagrant for it as well, but figured I would throw this out there for now.

**Comment by eseglem** [comment]
I have issued a separate pull request which uses a yaml config file instead which will not be OS dependent. That seems like a better alternative. Less interactive, but easier to support.

**Comment by eseglem** [comment]
Automatically closed because I moved code off of master branch. If wanted the code is still available at eseglem:install_files

**Pull request closed without merging**
